-- Mock 데이터 삽입: 97명의 채용 후보자 데이터

-- Developer (39명)
INSERT INTO candidates (name, position, skills, company) VALUES
('김민준', 'Developer', ARRAY['Python', 'Django', 'PostgreSQL'], '네이버'),
('박도윤', 'Developer', ARRAY['JavaScript', 'React', 'TypeScript'], '토스'),
('이재호', 'Developer', ARRAY['Java', 'Spring Boot', 'AWS'], '쿠팡'),
('최준호', 'Developer', ARRAY['Go', 'Kubernetes', 'Docker'], '카카오'),
('정한솔', 'Developer', ARRAY['Node.js', 'Express', 'MongoDB'], '당근마켓'),
('강민석', 'Developer', ARRAY['Python', 'FastAPI', 'Redis'], '네이버'),
('윤준호', 'Developer', ARRAY['Vue.js', 'TypeScript', 'Webpack'], '토스'),
('서준호', 'Developer', ARRAY['React', 'Next.js', 'Tailwind CSS'], '카카오'),
('임준호', 'Developer', ARRAY['Swift', 'iOS', 'UIKit'], '쿠팡'),
('홍준호', 'Developer', ARRAY['Kotlin', 'Android', 'Firebase'], '토스'),
('조준호', 'Developer', ARRAY['Flutter', 'Dart', 'Provider'], '당근마켓'),
('신준호', 'Developer', ARRAY['Machine Learning', 'Python', 'TensorFlow'], '네이버'),
('오준호', 'Developer', ARRAY['Blockchain', 'Solidity', 'Web3'], '두나무'),
('전준호', 'Developer', ARRAY['C++', 'Unreal Engine', 'Game Development'], '넥슨'),
('배준호', 'Developer', ARRAY['Java', 'Microservices', 'Kafka'], '쿠팡'),
('윤민호', 'Developer', ARRAY['Python', 'Celery', 'RabbitMQ'], '당근마켓'),
('정민호', 'Developer', ARRAY['Node.js', 'GraphQL', 'Apollo'], '카카오'),
('강민호', 'Developer', ARRAY['Go', 'gRPC', 'Protocol Buffers'], '네이버'),
('박민호', 'Developer', ARRAY['Rust', 'WebAssembly', 'Webpack'], '두나무'),
('이민호', 'Developer', ARRAY['PHP', 'Laravel', 'MySQL'], '당근마켓'),
('최민호', 'Developer', ARRAY['Python', 'Selenium', 'Pytest'], '네이버'),
('서민호', 'Developer', ARRAY['JavaScript', 'Cypress', 'Jest'], '토스'),
('임민호', 'Developer', ARRAY['Java', 'JUnit', 'Mockito'], '쿠팡'),
('홍민호', 'Developer', ARRAY['Go', 'testing', 'Benchmark'], '카카오'),
('조민호', 'Developer', ARRAY['React Native', 'JavaScript', 'Redux'], '당근마켓'),
('신민호', 'Developer', ARRAY['AWS', 'CloudFormation', 'Lambda'], '네이버'),
('오민호', 'Developer', ARRAY['Google Cloud', 'Terraform', 'Dataflow'], '토스'),
('전민호', 'Developer', ARRAY['Azure', 'Bicep', 'Azure DevOps'], '쿠팡'),
('배민호', 'Developer', ARRAY['Docker', 'Kubernetes', 'Helm'], '카카오'),
('윤준혁', 'Developer', ARRAY['CI/CD', 'Jenkins', 'GitLab Runner'], '당근마켓'),
('정준혁', 'Developer', ARRAY['Monitoring', 'Prometheus', 'Grafana'], '네이버'),
('강준혁', 'Developer', ARRAY['ELK Stack', 'Elasticsearch', 'Kibana'], '토스'),
('박준혁', 'Developer', ARRAY['Apache Kafka', 'Pub/Sub', 'Event Streaming'], '쿠팡'),
('이준혁', 'Developer', ARRAY['GraphQL', 'Apollo Server', 'Schema Design'], '카카오'),
('최준혁', 'Developer', ARRAY['REST API', 'OpenAPI', 'Swagger'], '당근마켓'),
('서준혁', 'Developer', ARRAY['WebSocket', 'Socket.io', 'Real-time'], '네이버'),
('임준혁', 'Developer', ARRAY['Authentication', 'OAuth 2.0', 'JWT'], '토스'),
('홍준혁', 'Developer', ARRAY['Payment Integration', 'Stripe', 'Toss Payments'], '쿠팡'),
('조준혁', 'Developer', ARRAY['SEO', 'Next.js SSR', 'Sitemap'], '카카오'),

-- Designer (20명)
('김미정', 'Designer', ARRAY['Figma', 'Sketch', 'Adobe XD'], '네이버'),
('이서윤', 'Designer', ARRAY['Figma', 'Prototyping', 'Design System'], '카카오'),
('박예진', 'Designer', ARRAY['Adobe XD', 'Wireframing', 'User Research'], '토스'),
('최소연', 'Designer', ARRAY['Figma', 'Animation', 'Lottie'], '쿠팡'),
('정지은', 'Designer', ARRAY['Sketch', 'Illustration', 'Branding'], '당근마켓'),
('강지은', 'Designer', ARRAY['Figma', 'Component Library', 'Design Tokens'], '네이버'),
('윤지은', 'Designer', ARRAY['Adobe XD', 'Motion Graphics', 'After Effects'], '토스'),
('서지은', 'Designer', ARRAY['Figma', 'Design System', 'Developer Handoff'], '카카오'),
('임지은', 'Designer', ARRAY['Sketch', 'User Testing', 'Heatmap'], '쿠팡'),
('홍지은', 'Designer', ARRAY['Adobe XD', 'Accessibility', 'WCAG'], '당근마켓'),
('조지은', 'Designer', ARRAY['Figma', '3D Design', 'Spline'], '네이버'),
('신지은', 'Designer', ARRAY['Sketch', 'Data Visualization', 'D3.js'], '토스'),
('오지은', 'Designer', ARRAY['Adobe XD', 'Game UI', 'Unreal'], '두나무'),
('전지은', 'Designer', ARRAY['Figma', 'Design Audit', 'A/B Testing'], '카카오'),
('배지은', 'Designer', ARRAY['Sketch', 'Typography', 'Font Design'], '당근마켓'),
('윤소연', 'Designer', ARRAY['Adobe XD', 'Icon Design', 'SVG'], '네이버'),
('정소연', 'Designer', ARRAY['Figma', 'Responsive Design', 'CSS'], '토스'),
('강소연', 'Designer', ARRAY['Sketch', 'Brand Guidelines', 'Style Guide'], '쿠팡'),
('박소연', 'Designer', ARRAY['Adobe XD', 'Interaction Design', 'Micro-interactions'], '카카오'),
('이소연', 'Designer', ARRAY['Figma', 'Design Collaboration', 'Feedback'], '당근마켓'),

-- PM (19명)
('최도윤', 'PM', ARRAY['Agile', 'Scrum', 'OKR'], '네이버'),
('박도윤', 'PM', ARRAY['Product Strategy', 'Jira', 'Confluence'], '토스'),
('이도윤', 'PM', ARRAY['SQL', 'Data Analysis', 'Tableau'], '쿠팡'),
('강도윤', 'PM', ARRAY['A/B Testing', 'Mixpanel', 'Amplitude'], '카카오'),
('윤도윤', 'PM', ARRAY['Lean Startup', 'User Stories', 'Roadmap'], '당근마켓'),
('서도윤', 'PM', ARRAY['Competitive Analysis', 'Market Research', 'Pricing'], '네이버'),
('임도윤', 'PM', ARRAY['E-commerce', 'Conversion Optimization', 'Funnel'], '토스'),
('홍도윤', 'PM', ARRAY['Fintech', 'Compliance', 'Regulations'], '쿠팡'),
('조도윤', 'PM', ARRAY['Healthcare', 'HIPAA', 'Telemedicine'], '카카오'),
('신도윤', 'PM', ARRAY['Gaming', 'Engagement', 'Retention'], '두나무'),
('오도윤', 'PM', ARRAY['Social Features', 'Community', 'Moderation'], '당근마켓'),
('전도윤', 'PM', ARRAY['Mobile First', 'App Analytics', 'Retention'], '네이버'),
('배도윤', 'PM', ARRAY['Growth Hacking', 'Viral Loop', 'Referral'], '토스'),
('윤서준', 'PM', ARRAY['Payment Strategy', 'Subscription', 'Monetization'], '쿠팡'),
('정서준', 'PM', ARRAY['Platform Economy', 'Marketplace', 'Commission'], '카카오'),
('강서준', 'PM', ARRAY['B2B', 'Enterprise Sales', 'SLA'], '당근마켓'),
('박서준', 'PM', ARRAY['API Design', 'Developer Experience', 'SDK'], '네이버'),
('이서준', 'PM', ARRAY['Analytics Setup', 'Event Tracking', 'Reporting'], '토스'),
('최서준', 'PM', ARRAY['Localization', 'I18n', 'Market Expansion'], '쿠팡'),

-- Marketer (19명)
('박지훈', 'Marketer', ARRAY['SEO', 'Google Analytics', 'Keyword Research'], '네이버'),
('이지훈', 'Marketer', ARRAY['Performance Marketing', 'Google Ads', 'Conversion'], '토스'),
('최지훈', 'Marketer', ARRAY['Content Strategy', 'Copywriting', 'Storytelling'], '쿠팡'),
('강지훈', 'Marketer', ARRAY['Social Media', 'Instagram', 'TikTok'], '카카오'),
('윤지훈', 'Marketer', ARRAY['Influencer Marketing', 'Partnership', 'Collaboration'], '당근마켓'),
('서지훈', 'Marketer', ARRAY['Email Marketing', 'Automation', 'Segmentation'], '네이버'),
('임지훈', 'Marketer', ARRAY['Growth Hacking', 'Viral Marketing', 'Network Effect'], '토스'),
('홍지훈', 'Marketer', ARRAY['Community Management', 'User Engagement', 'Moderation'], '쿠팡'),
('조지훈', 'Marketer', ARRAY['Brand Management', 'Brand Guidelines', 'Reputation'], '카카오'),
('신지훈', 'Marketer', ARRAY['Event Marketing', 'Conference', 'Sponsorship'], '당근마켓'),
('오지훈', 'Marketer', ARRAY['PR', 'Media Relations', 'Press Release'], '네이버'),
('전지훈', 'Marketer', ARRAY['Affiliate Marketing', 'Partnership', 'Commission'], '토스'),
('배지훈', 'Marketer', ARRAY['Conversion Rate Optimization', 'CRO', 'Landing Page'], '쿠팡'),
('윤서연', 'Marketer', ARRAY['Video Marketing', 'YouTube', 'Production'], '카카오'),
('정서연', 'Marketer', ARRAY['Marketing Analytics', 'Attribution', 'ROI'], '당근마켓'),
('강서연', 'Marketer', ARRAY['Programmatic Advertising', 'Real-time Bidding', 'DSP'], '네이버'),
('박서연', 'Marketer', ARRAY['Customer Retention', 'Loyalty Program', 'Churn'], '토스'),
('이서연', 'Marketer', ARRAY['Market Research', 'Survey', 'Focus Group'], '쿠팡'),
('최서연', 'Marketer', ARRAY['Partnership Marketing', 'Co-marketing', 'Cross-promotion'], '카카오');
